config/routes.rb
Rails.application.routes.draw do

  root 'images#index'
  get 'images', to: 'images#index'
  get 'images/:location/:page', to: 'images#image', as: 'show_image'
  get '(:search)', to: 'images#search', as: 'search'

end

app/models/image.rb
require 'open-uri'
require 'json'

class Image
	def initialize(options = {})
		@location = options[:location] || 'Washington DC'
		@last_time = options[:last_time]
		@CLIENT_ID 	=  Rails.application.secrets.CLIENT_ID
		@CLIENT_SECRET = Rails.application.secrets.CLIENT_SECRET
		#@ACCESS_TOKEN = '1602344324.1fb234f.5a9b17863e9f4642a2edab6f6126e566'
		@ACCESS_TOKEN = Rails.application.secrets.ACCESS_TOKEN
	end

	def set_location (location)
		@location = location
	end


	def example
		@json = "https://api.instagram.com/v1/tags/nofilter/media/recent?client_id=#{@CLIENT_ID}"
	end


	def get_images
		parse_instagram(@location, @last_time)
		@array = []
		@children = @json["data"].count - 1

		@children.times do |child|
			@array << [
			@json["data"][child]["images"]["standard_resolution"]["url"], 
			@json["data"][child]["link"], 
			@json["data"][child]["caption"],
			@json["data"][child]["created_time"]
		]
		end

		if @json["data"][@children-1].nil?
			@last_time = Time.now
		else
			@last_time = @json["data"][@children-1]["created_time"]
		end 

		return @array, @last_time
	end

	def parse_instagram(location, last_time)
		@last_time = last_time.to_i - 60
		@search = Location::GoogleAPI.new	
		@location_data = @search.set_location(location)
		@link = "https://api.instagram.com/v1/media/search?lat=#{@location_data[:lat]}&lng=#{@location_data[:lng]}&max_timestamp=#{@last_time}&access_token=#{@ACCESS_TOKEN}"
		@data = open(@link).read
		@json = JSON.parse(@data)

	end


	def last_image(array,max)
		#last element in the image array, third element in the envelope
		@last_time = array[max-1][2]["created_time"]
	end

end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@last_time = Time.now.to_i if @last_time.nil?
		@location = 'washington dc'
	end

	def image
		@location = params[:location]
		@image = Image.new(location: @location, last_time: params[:page])
		@images, @last_time = @image.get_images
		@count = @images.count
	end

	def search
		redirect_to show_image_path(location: (params[:location].blank? ? "Washington DC" : params[:location]) , page: Time.now.to_i)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/image.erb
<div class="centerize-image">
	<% if @count == 0 %>
		<div class="centerize">
			<h1>Doesnt look like anything is here!</h1>
			<p>Try being more specific with your location (i.e. "Tokyo, Japan")</p>
		</div>
		<% else %>
		<% @count.times do |count| %>
			<div class="box panel panel-default">
				<div class="image-container">
					<%=link_to image_tag(@images[count][0]), @images[count][1] %>
				</div>
				<div class="panel-footer centerize">
					<p><strong><%=Time.at(@images[count][3].to_i).strftime("%A, %B %m  | %l:%M%P") %></strong></p>
					<br>
					<% unless @images[count][2].nil? %>
						<p><strong><%= @images[count][2]["text"] %><strong></p>
					<% end %>

				</div>
			</div>
		<% end %>
		<br>
		<h3 class='centerize'><strong><%= link_to('MOAR', show_image_path(@location,@last_time)) %></strong></h3>
	<% end %>
	
</div>

app/views/images/index.erb
		<h1>Take a trip...</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AnotherLife</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link href='//fonts.googleapis.com/css?family=Lato:400,100italic' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
			<div class="navbar-nav">
				<div class="row">
					<h1 class='title'> another life </h1>
					<p>
					<%= form_tag(search_path(@location), method: "get") do %>
						<%= text_field_tag :location, params[:location], placeholder:"City, State, or Country" %>
						<%= submit_tag "Search Location", name: nil %>
					<% end %>
					</p>
				</div>
			</div>


	</div>
</div>

<div class="container-fluid">
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<%= yield %>
</div>
</div>

</body>
</html>